### ISSUE TITLE
Create 'docsify' template with dark theme

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#149]
Update dark css to look good on dark

**Comment by andrewmcodes** [comment]
I see a dark theme file in [here](https://github.com/andrewmcodes/code_fund_ads/tree/40b23846f9efbc671ab4a7463ecda487328f065c/app/views/ad_templates/docsify/themes). Is this still relevant?

**Comment by hopsoft** [comment]
Yep. It appears we just need to make it look nicer.

**Comment by andrewmcodes** [comment]
@hopsoft going to need some elaboration here. The docsify dark template appears to look just like the others. Is there something specific you can point out?

**Comment by andrewmcodes** [comment]
@coderberry here is what the dark docsify template looks like now. Could you let me know what you want to change? It looks pretty similar to our other dark templates so wasn't sure if there was something specific about this dark theme you wanted to change or if this issue was good to close.

![image](https://user-images.githubusercontent.com/18423853/66349320-96d3c200-e926-11e9-96b0-ce239160e829.png)

**Comment by coderberry** [comment]
@andrewmcodes that looks good. This may have been resolved already
