### ISSUE TITLE
Campaign card not showing full budget

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#463]
The campaign "card" does not update or include the full budget. See https://codefund.app/campaigns/214

![image](https://user-images.githubusercontent.com/12481/55900667-ece8c800-5b84-11e9-821e-317be7000932.png)

**Comment by hopsoft** [comment]
The campaign card show's the money remaining that can be spent on this campaign. If the __organization balance__ is lower than the money spent on this campaign _(relative to budget cap)_, we show the __organization balance__ instead.

This is because __campaign budget__ is something of a misnomer. It's really a __campaign budget cap__... as in _don't spend more than this_. But, less could be spent if the organization balance (i.e. available funds) is spread across multiple campaigns.

**Comment by hopsoft** [comment]
Perhaps we should relabel names.

- Max Budget Cap
- Daily Budget Cap
- Available Funds

**Comment by hopsoft** [comment]
We probably need another section along with the proposed renames.

- Money Spent on this Campaign

**Comment by coderberry** [comment]
I believe this works now that I ran the following code yesterday:

`Organization.all.map(&:recalculate_balance!)`

This likely wasn't run after we recalculated the daily spends
