### ISSUE TITLE
Multilingual sites cannot specify the language used

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#813]
When setting up a placement, I'm asked what language the content is in. The pages on my site can display in different languages depending on the locale in the URL. There's no way for me to specify this fact.

Ideally, the CodeFund JS would read the `<html lang>` of the page to know what language it actually is. Alternately, if there was a way to specify the language in the CodeFund snippet I put on my site, that would work too.

**Comment by andrewmcodes** [comment]
Awesome feedback. I’ll talk to the team about how we want to support this, but I think it’s important that we do.

**Comment by andrewmcodes** [comment]
@JasonBarnabe The property language is mostly used to indicate where the majority of your traffic is coming from. Since you have a website that is translated in several languages, please choose the one that best indicates the language the majority of your visitors speak/read.

Our advertising targeting is geo aware so the language you choose for your property only serves as a heuristic as part of the publisher approval process.
