### ISSUE TITLE
Date picker seems to be missing a dropdown arrow

### ISSUE THREAD

**Issue by jdorfman** [gitcoinco/code_fund_ads#939]
# Question

One of our awesome publishers was wondering why there's no dropdown arrow on the date picker.

## Details

Something like this: 

<img width="387" alt="Image 2019-12-16 at 2 12 38 PM" src="https://user-images.githubusercontent.com/398230/70947819-d990d500-200e-11ea-85b7-bc0f0f708da7.png">

## Additional context

The publisher brought this up to me with the older UI but I didn't file an issue because I assumed the UI/UX was going to fix it.

File under: Accessibility

**Comment by andrewmcodes** [comment]
@jdorfman I typically follow Google's [Material Design Guidelines](https://material.io/components/pickers/#theming) when thinking about UI components like this. I have done some additional research and it does not seem that a dropdown arrow is usually added to these types of inputs. 

A date picker is not actually a true dropdown. It is a specialized type of form input, usually referred to as a picker. Some interfaces have it just "drop down" from its input, others open in a modal, and we chose the former. Regardless of where it appears on the screen, the expectation of clicking on a date selection input is that you are presented with the ability to select a date, and I am not sure that adding a dropdown icon would add much to the user experience. 

That being said, I am not married to these ideas and if you think adding the dropdown indicator will help our users, I will add it. 🙂

**Comment by jdorfman** [comment]
I do see one here:

![image](https://user-images.githubusercontent.com/398230/70954785-6d6c9c00-2023-11ea-9fe4-a3abf56d7065.png)

as well as Google Analytics which I assume uses Material Design

<img width="385" alt="Image 2019-12-16 at 4 46 35 PM" src="https://user-images.githubusercontent.com/398230/70954870-c76d6180-2023-11ea-814a-5e812fe71a2a.png">

¯\_(ツ)_/¯

**Comment by andrewmcodes** [comment]
The difference is these inputs don't have the calendar icon, which is usually the indicator that it is a date picker. If more people ask for it in the future I am happy to add it but don't think we need to right now.

**Comment by jdorfman** [comment]
Sounds good thanks Andrew!

**Comment by wolfgang42** [comment]
For some context, here's the original conversation that prompted this issue:

@jdorfman 
> Hey Wolfgang!
>
> I just wanted to check in and see how everything is going.  If you ever have any questions please don't hesitate to reach out to me.
>
> Thanks for being apart of CodeFund!

@wolfgang42
> The "Estimated Earnings" number on my dashboard is steadily rising, which seems like a good sign. I am slightly confused, though, by the way everything seems to have reset to zero at the start of November. Is there a historical dashboard or something that I need to look at to see previous months?

@jdorfman 
>Hopefully this answers your question:
>![image](https://user-images.githubusercontent.com/2261204/71128267-b6e2f580-21a1-11ea-9b3f-9bd87f6e4921.png)
> "Custom Range" might be your best bet. Let me know if you have any other questions. =)

@wolfgang42
>Aha! That's exactly what I'm looking for, but I didn't realize it was clickable. (I think it would help if there was an arrow next to it to show that it was a dropdown.)
> Thanks for the help!

<hr/>

Even after the redesign I still think it needs an afforance to make it clear that this is something that can be interacted with. Maybe a dropdown arrow isn't the right thing, but I notice on the Material Design guidelines you linked the example date inputs are either obviously part of a form or have a [trailing icon](https://material.io/components/text-fields/#anatomy) such as a calendar or a pencil. The simplest fix might be to just move the calendar icon over to the right.

Obviously CodeFund isn't my project (and I'm not the one who has to answer support emails about this :slightly_smiling_face:), but I thought I'd weigh in and give a little extra context for why this came up. The only reason I thought to mention it to Justin is because I'd just been trying to figure it out right before I saw his email, and I'd guess that there are others who had the same problem but didn't think to mention it.
