### ISSUE TITLE
No impressions/revenue/anything reporting for Dec 31 2019

### ISSUE THREAD

**Issue by JasonBarnabe** [gitcoinco/code_fund_ads#971]
Dec 31 2019 shows as 0 impressions (paid or fallback) for all my properties. My site and ad code were up, so I'm guess it's something on your end.

**Comment by hopsoft** [comment]
This is due to our use of PostgreSQL table partitioning coupled with the current [flawed logic](https://github.com/gitcoinco/code_fund_ads/blob/master/app/models/impression.rb#L106-L115) that scopes old partition tables by year.

You can rest assured that we have the data for 2019-12-31 but it's sitting in a detached partition table. We will address this by reattaching 2019-12 tables and regenerating `daily_summaries`.

Note that there are other items in the queue before we can address this, so if we don't get to it in time for distributions, we'll credit you once it's been fixed. Thanks for your patience.

**Comment by andrewmcodes** [comment]
@hopsoft bump

**Comment by hopsoft** [comment]
The bug that caused this behavior was fixed by #1169
